# Generated by Django 5.0.1 on 2024-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortime',
            name='sick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
